import type { Metadata } from "next";
import { dir } from 'i18next';
import { languages } from '../../i18n/settings';
import './global.scss';
import localFont from 'next/font/local';
import { ReactNode } from "react";
import { Provider } from "../components/Providers";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

const helvetica = localFont({
  src: [
    {
      path: '../styles/fonts/HelveticaNeueCyr-Light.ttf',
      weight: '300'
    },
    {
      path: '../styles/fonts/HelveticaNeueCyr-Roman.ttf',
      weight: '400'
    },
    {
      path: '../styles/fonts/HelveticaNeueCyr-Medium.ttf',
      weight: '500'
    },
    {
      path: '../styles/fonts/HelveticaNeueCyr-Bold.ttf',
      weight: '700'
    },
  ]
});

export const metadata: Metadata = {
  title: "Friend Rate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng }
}: Readonly<{
  children: ReactNode;
  params: { lng: string }
}>) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={helvetica.className}>
       <Provider>
          {children}
       </Provider> 
      </body>
      
    </html>
  )
}
